name: Test Python package

on: [push]

# example borrowed from https://pythonpackaging.info/06-Continuous-Integration.html
# and https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-python

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f environment.yml ]; then pip install -r environment.yml; fi
    - name: Test it
      run: |
        chmod u+x ./test.sh
        ./test.sh true "Rmd"