name: Test Python scripts on simplest ubuntu setting

on: [pull_request]


# example borrowed from https://pythonpackaging.info/06-Continuous-Integration.html
# and https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-python
# and https://autobencoder.com/2020-08-24-conda-actions/

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}
          auto-update-conda: true
          auto-activate-base: false
          miniconda-version: 'latest'
      - shell: bash -l {0}
        run: |
          conda info
          conda list
      - name: Test it
        run: |
          chmod u+x ./test.sh
          ./test.sh true "Rmd"